"""new migrations

Revision ID: b5298298bb61
Revises: 1047d4d3abf1
Create Date: 2025-10-06 20:30:23.698662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5298298bb61'
down_revision: Union[str, Sequence[str], None] = '1047d4d3abf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['name'])
    op.create_unique_constraint(None, 'employees', ['name'])
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'phone_number')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
